//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Inputs/Inputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Inputs : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Inputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Inputs"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""98e452a6-576e-4676-9c46-7082291e0114"",
            ""actions"": [
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""f21803de-5437-43ea-a635-e589df795050"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeToGunShootLimit"",
                    ""type"": ""Button"",
                    ""id"": ""f1330a68-319f-44dd-a42e-b4c315748a1e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChangeToGunShootAngle"",
                    ""type"": ""Button"",
                    ""id"": ""7292e18d-3807-4e4b-95e5-b09339c1fee2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""348863d9-4294-4d78-b17d-193908aef76b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d100772-5339-4f3f-8122-08329adf1660"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeToGunShootLimit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e4472ab5-475a-4174-8c44-14afe4560170"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChangeToGunShootAngle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_Shoot = m_Gameplay.FindAction("Shoot", throwIfNotFound: true);
        m_Gameplay_ChangeToGunShootLimit = m_Gameplay.FindAction("ChangeToGunShootLimit", throwIfNotFound: true);
        m_Gameplay_ChangeToGunShootAngle = m_Gameplay.FindAction("ChangeToGunShootAngle", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_Shoot;
    private readonly InputAction m_Gameplay_ChangeToGunShootLimit;
    private readonly InputAction m_Gameplay_ChangeToGunShootAngle;
    public struct GameplayActions
    {
        private @Inputs m_Wrapper;
        public GameplayActions(@Inputs wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot => m_Wrapper.m_Gameplay_Shoot;
        public InputAction @ChangeToGunShootLimit => m_Wrapper.m_Gameplay_ChangeToGunShootLimit;
        public InputAction @ChangeToGunShootAngle => m_Wrapper.m_Gameplay_ChangeToGunShootAngle;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @Shoot.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnShoot;
                @ChangeToGunShootLimit.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeToGunShootLimit;
                @ChangeToGunShootLimit.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeToGunShootLimit;
                @ChangeToGunShootLimit.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeToGunShootLimit;
                @ChangeToGunShootAngle.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeToGunShootAngle;
                @ChangeToGunShootAngle.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeToGunShootAngle;
                @ChangeToGunShootAngle.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnChangeToGunShootAngle;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @ChangeToGunShootLimit.started += instance.OnChangeToGunShootLimit;
                @ChangeToGunShootLimit.performed += instance.OnChangeToGunShootLimit;
                @ChangeToGunShootLimit.canceled += instance.OnChangeToGunShootLimit;
                @ChangeToGunShootAngle.started += instance.OnChangeToGunShootAngle;
                @ChangeToGunShootAngle.performed += instance.OnChangeToGunShootAngle;
                @ChangeToGunShootAngle.canceled += instance.OnChangeToGunShootAngle;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnShoot(InputAction.CallbackContext context);
        void OnChangeToGunShootLimit(InputAction.CallbackContext context);
        void OnChangeToGunShootAngle(InputAction.CallbackContext context);
    }
}
